apiVersion: v1
kind: Service
metadata:
  name: llmops-service
  namespace: llmops
  labels:
    app: llmops-server
spec:
  selector:
    app: llmops-server
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP   # use LoadBalancer for cloud; NodePort for minikube
